[project]
name = "gentleman"
version = "1.0.0"
dependencies = [
    "requests"
]

[project.scripts]
gentleman = "gentleman.__main__:main"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
namespaces = false
